# Generated by Django 4.0 on 2024-01-04 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YSE_App', '0008_frbtransient_dm_ism'),
    ]

    operations = [
        migrations.AddField(
            model_name='frbtransient',
            name='eventid',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
