# Generated by Django 4.0 on 2025-09-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YSE_App', '0010_frbsamplecriteria_apply_bright_star_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frbsamplecriteria',
            name='skip_need_image',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
