# Generated by Django 4.0 on 2026-03-06 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('YSE_App', '0011_frbsamplecriteria_skip_need_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='frbsamplecriteria',
            name='override_blocking_statuses',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='frbtransient',
            name='repeater_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='frbtransient',
            name='repeater_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='FRBGiveUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('reason', models.TextField()),
                ('date', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to='auth.user')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified_by', to='auth.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
